//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_2018.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proiect_2018.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0013623 {
            get {
                object obj = ResourceManager.GetObject("_0013623", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100deAni {
            get {
                object obj = ResourceManager.GetObject("_100deAni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Lynxul polar
        ///Toată populația din această specie este estimată la 55.000 de indivizi, din care majoritatea trăiește în Rusia.Lynxii au mărimea asemănătoare cu cea a câinelui. Au între 70 și 150 cm lungime, cu coadă  scurtă — de 5–25 cm. Vârful cozii  este de obicei negru, iar în vârful urechilor sunt smocurile de peri negri.De asemenea,au perii albi la piept, pântece.Greutățile maxime raportate se găsesc între 50 kg și 58 kg.Lynxii au gheare ascuțite și retractile care ajung lungimea de 4–6 cm. Lynxii tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Animalepolare {
            get {
                return ResourceManager.GetString("Animalepolare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundJungla {
            get {
                object obj = ResourceManager.GetObject("BackgroundJungla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bioparc_valencia2 {
            get {
                object obj = ResourceManager.GetObject("bioparc_valencia2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descărcare {
            get {
                object obj = ResourceManager.GetObject("descărcare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descărcare__1_ {
            get {
                object obj = ResourceManager.GetObject("descărcare__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descărcare1 {
            get {
                object obj = ResourceManager.GetObject("descărcare1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Găina
        ///Găina este o pasăre domestică.Este crescută pentru carne și ouă.Masculul găinii se numește cocoș. El este mai mare decât femela, are un penaj multicolor, o creastă și bărbie roșie.
        ///2
        ///Rața
        ///Rața este o  pasăre de apă.Majoritatea rațelor au un cioc lung și lat, folosit la săpat. Rațele au un meniu divers; pot consuma ierburi, plante acvatice, pești, insecte, amfibieni mici, viermi și moluște mici.De la ele se folosesc carnea, ouăle dar și penele.
        ///3
        ///Vaca
        ///Vaca este un animal domestic.Vacile sunt  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FermaAnimalelor {
            get {
                return ResourceManager.GetString("FermaAnimalelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Harta_Romaniei {
            get {
                object obj = ResourceManager.GetObject("Harta_Romaniei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2_ {
            get {
                object obj = ResourceManager.GetObject("images__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images2 {
            get {
                object obj = ResourceManager.GetObject("images2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Tigrul
        ///Tigrul este o specie de mamifere carnivore.Este unul dintre cei mai mari răpitori tereștri.Tigrilor le sunt caracteristice dungile de culoare închisă.Este dotat cu colți lungi și maxilare puternice, vedere nocturnă de șase ori mai bună decât a omului.Pot vâna și maimuțe, păsări, pești și chiar alte răpitoare, ca lupii, leoparzii și crocodilii.Tigrul reprezintă un simbol al puterii.
        ///2
        ///Jaguarul
        ///Jaguarul este una din marile feline.Animal musculos, jaguarul are, la maturitate, 59-96 kilograme. Mas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoJungla {
            get {
                return ResourceManager.GetString("InfoJungla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lectia3 {
            get {
                object obj = ResourceManager.GetObject("lectia3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Ariciul
        ///Ariciul este un mamifer mic care aparține ordinului insectivorelor, având o lungime a corpului de până la 33 de cm. Greutatea variază de la 800-1200g. Ei au membre mici și puternice, membrele posterioare fiind puțin mai mari și musculoase ca cele anterioare. Membrele au câte 5 degete, unde primul și ultimul deget sunt mai mici în comparație cu celelalte degete și nu au gheare. Au niște ochi mici și o ureche  slab dezvoltată. Au un bot mic și ascuțit, cu foarte dezvoltat. Partea dorsală și latera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MamifereRomania {
            get {
                return ResourceManager.GetString("MamifereRomania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap padure_din_muntii_carpati {
            get {
                object obj = ResourceManager.GetObject("padure_din_muntii_carpati", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Barza
        ///Barza este o pasăre migratoare cu ciocul, gâtul și picioarele foarte lungi.Iernează în Africa.Populația în România este de 5.000-6.000 de perechi. Barza albă este o pasăre mare cu o lungime a corpului de 110-115 cm și o greutate de 2700-4500 g.Trăiește maxim  39 de ani. Are ciocul roșu, lung, ascuțit la vârf și picioarele lungi, roșii. Barza albă se hrănește cu broaște, mormoloci, pești, șerpi și șopârle, insecte, viermi, melci, șoareci, cârtițe, pui de păsări și de iepuri.
        ///2
        ///Cinteza
        ///Cinteza  e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasariRomania {
            get {
                return ResourceManager.GetString("PasariRomania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polar {
            get {
                object obj = ResourceManager.GetObject("polar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap polar2 {
            get {
                object obj = ResourceManager.GetObject("polar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap punct {
            get {
                object obj = ResourceManager.GetObject("punct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///Țestoasa de uscat
        ///În România, trăiește în pădurile și regiunile de stepă din Oltenia, Banat și Dobrogea.Țestoasa de uscat se recunoaște după corpul ei scurt, acoperit cu un țest format din 2 părți:carapacea (la partea superioară, bombată, de culoare maroniu-roșcat),plastronul (la partea inferioară, de culoare deschisă).Ele sunt unite pe laturi, lăsând 2 deschizaturi prin care ies capul și membrele anterioare.Se hrănește cu ierburi salbatice, fructe, insecte, melci și viermi pe care le taie cu marginea c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReptileRomania {
            get {
                return ResourceManager.GetString("ReptileRomania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sageata {
            get {
                object obj = ResourceManager.GetObject("sageata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tigru {
            get {
                object obj = ResourceManager.GetObject("tigru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZooHub {
            get {
                object obj = ResourceManager.GetObject("ZooHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
